# -*- mode: ruby -*-
# vi: set ft=ruby :

# VERSÃO DAS BOXES USADAS
os = 'centos/7'
hostname = 'Simple-CentOS'

# PASTA SINCRONIZADA
syncedFolderConf = false
syncedFolderOrigin = "D:/8 - Infraestrutura/"
syncedFolderDestiny = "/home/infra/"

# CONFIG DA VM
Vagrant.configure("2") do |config|
  config.vm.box = os
  config.vm.hostname = hostname
  config.vm.synced_folder syncedFolderOrigin, syncedFolderDestiny, disabled: syncedFolderConf
  config.vm.provider "virtualbox" do |vb|
      vb.name = hostname
      vb.memory = 1024
      vb.cpus = 2
  end
end
